server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mentoring
    username: root
    password: 9162
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug